name: Connect to AWS EC2

on:
  push:
    branches:
      - main  # Adjust to your branch name 

jobs:
  connect-to-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install AWS CLI
      run: |
        if ! command -v aws &>/dev/null; then
          curl "https://d1vvhvl2y92vvt.cloudfront.net/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        fi
      if: success()


    - name: SSH into EC2
      run: |
        pwd
        ls
        ssh -tt -o StrictHostKeyChecking=no -i "js-us-west-2-kp.pem" ec2-user@ec2-34-215-228-84.us-west-2.compute.amazonaws.com
        #ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ec2-user@34.215.228.84
      env:
        EC2_INSTANCE_IP: "34.215.228.84"
      if: success()
