name: SSH to AWS VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      env:
        PRIVATE_KEY: ${{ secrets.YOUR_SSH_SECRET_NAME }}
      run: |
        mkdir -p ~/.ssh
        cat js-us-west-2-kp.pem > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan ec2-34-215-228-84.us-west-2.compute.amazonaws.com >> ~/.ssh/known_hosts

    - name: SSH into EC2 Instance
      run: ssh -i ~/.ssh/id_rsa ec2-user@ec2-34-215-228-84.us-west-2.compute.amazonaws.com

    - name: execute cmd
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@$ec2-34-215-228-84.us-west-2.compute.amazonaws.com "pwd && whoami"
        #ssh -i ~/.ssh/id_rsa ec2-user@$EC2_INSTANCE_IP "cd /path/to/your/project/folder/your-repo && ls"
